name: CI
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v11
        with:
          java-version: openjdk@1.17
      - name: Compile
        run: sbt compile
      - name: Test
        run: sbt test
